apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: odd 
  janus-idp.io/tekton: odd
  backstage.io/kubernetes-id: odd
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: odd
resources: 
- application-dev.yaml